# Color support and italics. This must be created
set -g default-terminal "tmux-256color" 

# Remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# Change leader key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Bind splitting
unbind %
bind | split-window -h

unbind '"'
bind '\' split-window -v

# Bind resizing
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Full window panel model
bind -r m resize-pane -Z

# Mouse interaction enabled
set -g mouse on

# Copy mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# Plugins
set -g @plugin 'tmux-plugins/tpm' # Tmux Plugin Manager

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect' # Prefix + C-s: Save ~ Prefix + C-r: Restore

## Theme
set -g @themepack 'basic'

# Run TPM ~ Keep this at the very bottom of the conf file
run '~/.tmux/plugins/tpm/tpm'
