;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #00000000
background-alt = #E6E6E6
foreground = #E6E6E6
active = #ab0ea3
disabled = #707880

[bar/top]
width = 100%
height = 24pt
radius = 6
dpi = 96
enable-ipc = true

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 2pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 3

separator = |
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font:size=11;0

modules-center = date
modules-left = i3-mode
modules-right = pulseaudio xkeyboard memory cpu wlan eth systray

cursor-click = pointer
cursor-scroll = ns-resize

tray-position = right

[bar/bottom]
width = 100%
height = 24

background = ${colors.background}
foreground = ${colors.foreground}

bottom = true
font-0 = JetBrainsMono Nerd Font:size=11:weight=bold;0

modules-center = xwindow
modules-left = i3

padding-right = 8

line-size = 4

[module/i3]
type = internal/i3

format = <label-state>
show-urgent = true

label-focused = %name%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background}
label-focused-underline = ${colors.active}
label-focused-padding = 4

label-unfocused = %name%
label-unfocused-padding = 4

label-visible = %name%

label-urgent = %name%
label-urgent-padding = 4

[module/i3-mode]
type = internal/i3

format =  <label-mode>

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xwindow]
type = internal/xwindow
label = %title%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>

label-volume = %percentage%%

label-muted = 󰸈
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.foreground}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.foreground}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.foreground}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
date = 󰥔  %%{F#99}%Y-%m-%d%%{F-}
date-alt = %%{F#fff}%A, %d %B %Y  

time = %%{F#fff}%H:%M%%{F-}
time-alt = %%{F#fff}%H:%M%%{F#666}:%%{F#fba922}%S%%{F-}

label = %date%   %time%
label-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
